import { z } from "zod";

import type { SignalSummary } from "./signals";

/**
 * The detection prompt and its response schema.
 *
 * Two deliberate choices here.
 *
 * First, the model is never asked for character offsets — only for the index of
 * a paragraph it was given. Offsets are computed server-side from the same split
 * that produced the numbered list, so highlighting is exact rather than
 * dependent on a model counting characters.
 *
 * Second, the instructions require calibration and forbid certainty. An AI
 * detector that returns 97% on a non-native speaker's honest essay is worse
 * than useless — it is actively harmful to that student. The prompt says so.
 */

export const detectionResponseSchema = z.object({
  estimated_ai_likelihood: z
    .number()
    .min(0)
    .max(100)
    .describe("Estimated likelihood, 0-100, that this text was AI-generated."),
  summary: z
    .string()
    .max(600)
    .describe(
      "Two or three sentences describing the writing patterns observed, hedged appropriately.",
    ),
  paragraphs: z
    .array(
      z.object({
        index: z.number().int().min(0).describe("The paragraph number given."),
        estimated_ai_likelihood: z.number().min(0).max(100),
        rationale: z
          .string()
          .max(300)
          .describe("One sentence on what was observed in this paragraph."),
      }),
    )
    .describe("One entry per paragraph supplied, in the same order."),
});

export type DetectionResponse = z.infer<typeof detectionResponseSchema>;

export const DETECTION_SYSTEM_PROMPT = `You analyse writing and estimate how likely it is to have been generated by a large language model.

You are one input into a writing tool used by students, researchers, educators and professional writers. Your output is shown as an *estimate*, never as proof of authorship, and the people reading it may be making consequential decisions. Calibrate accordingly.

What to weigh:
- Sentence rhythm. Human drafts usually vary sentence length markedly; generated prose tends toward even, mid-length sentences.
- Lexical texture. Unusual word choices, idiom, inconsistent register and small infelicities suggest a human draft.
- Structural uniformity. Paragraphs of near-identical length and shape, each opening with a connective, is a common generated pattern.
- Content specificity. Concrete detail, named sources, personal observation and genuine hedging are harder to generate and more common in human work.
- Repetition. Recycled phrasing and restated claims across paragraphs.

Critical constraints on your judgement:
- Formal, polished, well-organised writing is NOT evidence of generation. Competent academic prose looks like this.
- Non-native English writers frequently produce even, simple sentence structures and lean on formal connectives. This must NOT push your estimate up. Getting this wrong causes real harm to real students.
- Technical, legal and scientific writing is repetitive and formulaic by convention.
- Text that has been edited, translated, or written with grammar-checking assistance sits legitimately in the middle.
- Short passages carry little signal. Stay near the middle of the range unless the evidence is strong.

Use the full range, but reserve estimates above 85 for text showing multiple strong indicators at once, and below 15 for text with clear human texture. When the evidence is genuinely mixed, say so and score in the middle rather than guessing.

Write the summary in plain language for a non-specialist. Describe what you observed in the writing. Never assert that the text was written by AI, never address the reader as though they are suspected of anything, and never recommend an academic-integrity action.`;

/** Builds the per-request prompt: the measurements, then the numbered text. */
export function buildDetectionPrompt(params: {
  paragraphs: string[];
  signals: SignalSummary;
}): string {
  const { paragraphs, signals } = params;

  const measurements = [
    `- Words: ${signals.wordCount}`,
    `- Sentences: ${signals.sentenceCount}`,
    `- Mean sentence length: ${signals.meanSentenceLength} words`,
    `- Sentence length standard deviation: ${signals.sentenceLengthVariation}`,
    `- Unique words as a share of total: ${(signals.lexicalDiversity * 100).toFixed(1)}%`,
    `- Four-word sequences occurring more than once: ${(signals.repeatedPhraseRate * 100).toFixed(1)}%`,
    `- Varied punctuation per 100 words: ${signals.punctuationVariety}`,
    `- Formal connectives per 1,000 words: ${signals.connectiveDensity}`,
  ].join("\n");

  const numbered = paragraphs
    .map((paragraph, index) => `[${index}]\n${paragraph}`)
    .join("\n\n");

  return `Measurements computed from this text:

${measurements}

Return one entry for every paragraph below, using the number in brackets as the index. Do not merge, split, skip or reorder paragraphs.

---

${numbered}`;
}
